package com.rhdemo.smartcase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Alert implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("Temperature")
	private java.lang.Integer temperature;
	@org.kie.api.definition.type.Label("Humidity")
	private java.lang.Integer humidity;
	@org.kie.api.definition.type.Label("Trigger")
	private boolean trigger;

	@org.kie.api.definition.type.Label("Asset ID")
	private java.lang.String assetId;

	@org.kie.api.definition.type.Label("Asset Information")
	private com.rhdemo.smartcase.AssetInfo assetInfo;

	public Alert() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.Integer getTemperature() {
		return this.temperature;
	}

	public void setTemperature(java.lang.Integer temperature) {
		this.temperature = temperature;
	}

	public java.lang.Integer getHumidity() {
		return this.humidity;
	}

	public void setHumidity(java.lang.Integer humidity) {
		this.humidity = humidity;
	}

	public boolean isTrigger() {
		return this.trigger;
	}

	public void setTrigger(boolean trigger) {
		this.trigger = trigger;
	}

	public java.lang.String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(java.lang.String assetId) {
		this.assetId = assetId;
	}

	public com.rhdemo.smartcase.AssetInfo getAssetInfo() {
		return this.assetInfo;
	}

	public void setAssetInfo(com.rhdemo.smartcase.AssetInfo assetInfo) {
		this.assetInfo = assetInfo;
	}

	public Alert(java.lang.String status, java.lang.Integer temperature,
			java.lang.Integer humidity, boolean trigger,
			java.lang.String assetId, com.rhdemo.smartcase.AssetInfo assetInfo) {
		this.status = status;
		this.temperature = temperature;
		this.humidity = humidity;
		this.trigger = trigger;
		this.assetId = assetId;
		this.assetInfo = assetInfo;
	}

}