package com.rhdemo.smartcase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AssetInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Type")
	private java.lang.String type;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "Location")
	private java.lang.String location;

	public AssetInfo() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public AssetInfo(java.lang.String type, java.lang.String name,
			java.lang.String location) {
		this.type = type;
		this.name = name;
		this.location = location;
	}

}